jobs:
  test-kvm:
    runs-on: ubuntu-latest
    steps:
      - name: Check if /dev/kvm exists
        run: |
          if [ -e /dev/kvm ]; then
            echo "✅ /dev/kvm exists"
          else
            echo "❌ /dev/kvm not found"
            exit 1
          fi

      - name: Check if user can access /dev/kvm
        run: |
          echo "Trying: cat /dev/kvm"
          sudo cat /dev/kvm || echo "❌ Permission denied"

      - name: Check nested virtualization
        run: |
          if [ -f /sys/module/kvm_intel/parameters/nested ]; then
            echo "Nested virtualization (Intel): $(cat /sys/module/kvm_intel/parameters/nested)"
          elif [ -f /sys/module/kvm_amd/parameters/nested ]; then
            echo "Nested virtualization (AMD): $(cat /sys/module/kvm_amd/parameters/nested)"
          else
            echo "❌ No nested virtualization config found"
          fi

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Run QEMU without KVM
        run: |
          echo "Running QEMU without -enable-kvm (should work)"
          qemu-system-x86_64 --version

      - name: Run QEMU with KVM (expected to fail)
        run: |
          echo "Running QEMU with -enable-kvm (should fail)"
          sudo qemu-system-x86_64 -enable-kvm -nographic -vga none -kernel /bin/true || echo "❌ QEMU KVM failed as expected"
